
package Aplikasi;
import DBconfig.MahasiswaManager;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class JendelaUtama extends javax.swing.JFrame {
    private Connection coon;
   

    /**
     * Creates new form JendelaUtama
     */
    public JendelaUtama() {
        initComponents();
        coon = MahasiswaManager.getConnection();
        getData();
    }
    private void getData(){
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);
        
        try{
            String sql = "select* from tbl_mahasiswa";
            PreparedStatement st = coon.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            
            SimpleDateFormat DF = new SimpleDateFormat("yyyy-MM-dd");
            while(rs.next()){
                String NoBP = rs.getString("No_BP");
                String Nama = rs.getString("Nama");
                String TmtLahir = rs.getString("Tempat_Lahir");
                String Alamat = rs.getString("Alamat");
                String Telpon = rs.getString("Telp");
                String AsalSekolah = rs.getString("Asal_Sekolah");

                String Tgl =rs.getString("Tanggal_Lahir");
                Date TglLahir = null;

                if(TglLahir != null){
                   TglLahir = new Date(DF.parse(Tgl).getTime());
               }
                Object[] rowData = {NoBP,Nama,TmtLahir,Tgl,Alamat,Telpon,AsalSekolah};
                model.addRow(rowData);
            }   
            rs.close();
            st.close();
        }catch (Exception e) {
            Logger.getLogger(JendelaUtama.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNoBP = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTmtLahir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTelpon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tfAsalSekolah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTglLahir = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DataMahasiswa"));

        tblData.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NoBP", "Nama", "TmtLahir", "TglLahir", "Alamat", "Telpon", "AsalSekolah"
            }
        ));
        tblData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblData.setGridColor(new java.awt.Color(204, 204, 204));
        tblData.setRowHeight(30);
        tblData.setRowSelectionAllowed(true);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel1.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel2.setText("NoBP");

        tfNoBP.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N

        tfNama.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel3.setText("Tempat/TglLahir");

        tfTmtLahir.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel5.setText("NoTelpon");

        tfTelpon.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        tfTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelponActionPerformed(evt);
            }
        });

        taAlamat.setColumns(20);
        taAlamat.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        jLabel6.setText("/");

        tfAsalSekolah.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        tfAsalSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsalSekolahActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel8.setText("AsalSekolah");

        tfTglLahir.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N

        btnNew.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnNew.setText("Baru");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        btnPrev.setText("Kembali");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNoBP)
                            .addComponent(tfNama)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTmtLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTglLahir))
                            .addComponent(jScrollPane2)
                            .addComponent(tfAsalSekolah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelpon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev))
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTmtLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrev)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tblData.getSelectedRow();
        if (selectedRow!=-1) {
            if(btnDelete.getText().equals("Hapus")){
                int respon = JOptionPane.showConfirmDialog(this,"Beneran Mau Dihapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);

                if (respon == 0){
                    String NoBP = tfNoBP.getText();
                    String Nama = tfNama.getText();

                    if (NoBP.isEmpty()|| Nama.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "kolom harus diisi", "informasi", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    try{
                        String cmdSql = "Delete from tbl_mahasiswa where No_BP = ?;";
                        PreparedStatement preStat = coon.prepareStatement(cmdSql);

                        preStat.setString(1,NoBP);

                        int RowInsert = preStat.executeUpdate();
                        if (RowInsert >0 ){
                            JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus","informasi",JOptionPane.INFORMATION_MESSAGE);
                            resetForm();
                            getData();

                        } else{
                            JOptionPane.showMessageDialog(this,"Gagal Menghapus Data","informasi",JOptionPane.ERROR_MESSAGE);
                        }

                        preStat.close();

                    } catch  (Exception e){
                        JOptionPane.showMessageDialog(this,"Terjadi Kesalahan:" + e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(JendelaUtama.class.getName()).log(Level.SEVERE,null,e);
                    }

                    resetForm();
                }
            }
        }
    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = tblData.getSelectedRow();
        if (selectedRow!=-1){

            if (btnEdit.getText().equals("Edit")){
                tfNoBP.setEditable(true);
                tfNama.setEditable(true);
                tfTmtLahir.setEditable(true);
                tfTglLahir.setEditable(true);
                taAlamat.setEditable(true);
                tfTelpon.setEditable(true);
                tfAsalSekolah.setEditable(true);
                btnEdit.setText("Simpan");
            } else if (btnEdit.getText().equals("Simpan")){
                String NoBP = tfNoBP.getText();
                String Nama = tfNama.getText();
                String TmtLahir = tfTmtLahir.getText();
                String TglLahir = tfTglLahir.getText();
                String Alamat = taAlamat.getText();
                String Telpon = tfTelpon.getText();
                String AsalSekolah = tfAsalSekolah.getText();

                if (NoBP.isEmpty()|| Nama.isEmpty()){
                    JOptionPane.showMessageDialog(this,"kolom harus diisi","informasi",JOptionPane.ERROR_MESSAGE);
                    return;
                }

                try{
                    String cmdSql = "update tbl_mahasiswa set Nama = ?, Tempat_Lahir = ?, Tanggal_Lahir = ?, Alamat = ?, Telp = ?, Asal_Sekolah = ? where No_BP = ?;";
                    PreparedStatement preStat = coon.prepareStatement(cmdSql);

                    preStat.setString(1, Nama);
                    preStat.setString(2, TmtLahir);
                    preStat.setString(3, TglLahir);
                    preStat .setString(4, Alamat);
                    preStat.setString(5, Telpon);
                    preStat.setString(6, AsalSekolah);
                    preStat.setString(7, NoBP);

                    int rowInsert = preStat.executeUpdate();
                    if (rowInsert > 0){
                        JOptionPane.showMessageDialog(this, "Data Update Berhasil Disimpan","informasi", JOptionPane.INFORMATION_MESSAGE);
                        resetForm();
                        getData();

                    } else{
                        JOptionPane.showMessageDialog(this, "Gagal Meng-update data","Erro",JOptionPane.ERROR_MESSAGE);
                    }
                    preStat.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Terjadi Kesalahan:" + e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(JendelaUtama.class.getName()).log(Level.SEVERE,null,e);
                }

                btnEdit.setText("Edit");
                resetForm();

            }

        } else{
            JOptionPane.showMessageDialog(this, "pilih data terlebih dahulu dari tabel","informasi",JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        String NoBP = tfNoBP.getText();
        String nama = tfNama.getText();
        String TmtLahir = tfTmtLahir.getText();
        String TglLahir = tfTglLahir.getText();
        String Alamat = taAlamat.getText();
        String Telpon = tfTelpon.getText();
        String AsalSekolah =tfAsalSekolah.getText();

        if(NoBP.isEmpty() || nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi","Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            String sql = "INSERT INTO tbl_mahasiswa (No_BP, Nama, Tempat_Lahir, Tanggal_Lahir, Alamat, Telp, Asal_Sekolah) values (?,?,?,?,?,?,?)";
            PreparedStatement st = coon.prepareStatement(sql);

            st.setString(1,NoBP);
            st.setString(2,nama);
            st.setString(3,TmtLahir);
            st.setString(4,TglLahir);
            st.setString(5,Alamat);
            st.setString(6,Telpon);
            st.setString(7,AsalSekolah);

            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                resetForm();
                getData();
            }
            st.close();
        } catch (Exception e) {
            Logger.getLogger(JendelaUtama.class.getName()).log(Level.SEVERE,null,e);

        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void tfAsalSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsalSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsalSekolahActionPerformed

    private void tfTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelponActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int row = tblData.getSelectedRow();

        if (row !=-1){
            String NoBP = tblData.getValueAt (row, 0).toString();
            String Nama = tblData.getValueAt(row,1 ).toString();
            String Tmt_Lahir = tblData.getValueAt(row,2).toString();
            String Tgl_Lahir = tblData.getValueAt(row,3).toString();
            String Alamat = tblData.getValueAt(row,4).toString();
            String Telpon = tblData.getValueAt(row,5).toString();
            String Asal_Sekolah = tblData.getValueAt(row,6).toString();

            
            tfNama.setText(Nama);
            tfTmtLahir.setText(Tmt_Lahir);
            tfTglLahir.setText(Tgl_Lahir);
            taAlamat.setText(Alamat);
            tfTelpon.setText(Telpon);
            tfAsalSekolah.setText(Asal_Sekolah);

            tfNoBP.setEditable(false);
            tfNama.setEditable(false);
            tfTmtLahir.setEditable(false);
            tfTglLahir.setEditable(false);
            taAlamat.setEditable(false);
            tfTelpon.setEditable(false);
            tfAsalSekolah.setEditable(false);

            btnNew.setEnabled(false);

        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
       resetForm();
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JendelaUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField tfAsalSekolah;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoBP;
    private javax.swing.JTextField tfTelpon;
    private javax.swing.JTextField tfTglLahir;
    private javax.swing.JTextField tfTmtLahir;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        tfNoBP.setText("");
        tfNama.setText("");
        tfTmtLahir.setText("");
        tfTglLahir.setText("");
        taAlamat.setText("");
        tfTelpon.setText("");
        tfAsalSekolah.setText("");

        //mengaktifkan feild
        tfNoBP.setEditable(true);
        tfNama.setEditable(true);
        tfTmtLahir.setEditable(true);
        tfTglLahir.setEditable(true);
        taAlamat.setEditable(true);
        tfTelpon.setEditable(true);
        tfAsalSekolah.setEditable(true);

        //mengaktifkan button baru
        btnNew.setEnabled(true);
        
    }
}
